config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/profiles", to: "profiles#index", as: "profiles"
  post "/profiles", to: "profiles#create"
  get "/profiles/new", to: "profiles#new", as: "new_profile"
  get "/profiles/:id", to: "profiles#show", as: "profile"
  put "/profiles/:id", to: "profiles#update"
  patch "/profiles/:id", to: "profiles#update"
  delete "/profiles/:id", to: "profiles#destroy"
  get "/profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_many :addresses, dependent: :destroy
    accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: :all_blank
end

app/controllers/address_controller.rb
class AddressesController < ApplicationController

def index 
end

def destroy
  @profile.addresses.delete(@address)
end

private

def set_address 
  profile = Profile.find(params[:id])
  @address = profile.addresses(params[:addresses][:id])
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:show, :edit, :update, :destroy]

    def index
        @profiles = Profile.all
    end

    def show
    end

    def new
        @profile = Profile.new
        2.times { @profile.addresses.build }
    end

    def create
        @profile = Profile.create(profile_params)
        redirect_to @profile
        #finish logic for creating a record
    end

    def edit

    end

    def update
        #finsih logic for updating the record
        @profile.update(profile_params)
        redirect_to profiles_path
    end

    def destroy
        #finish logic for deleting the record
        @profile.destroy
        redirect_to profiles_path
    end

    private

    def set_profile
        id = params[:id]
        @profile = Profile.find(id)
    end

    def profile_params
        params.require(:profile).permit(:name, :age, :bio, addresses_attributes: [:street, :city, :state, :postcode])
        # .merge(profile_id: current_profile.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChallengeTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with model: profile do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br><br>
    <%= form.label :age %>
    <%= form.number_field :age, min:1 %>
    <br><br>
    <%= form.label :bio %>
    <%= form.text_area :bio, size: "30x4", autofocus: true, placeholder: 'Tell us about yourself' %>
    <br><br>
    <p>Addresses:</p>
    <ul>
    <%= form.fields_for :addresses do |addresses_form| %>
        <li>
            <%= addresses_form.label :street %>
            <%= addresses_form.text_field :street %>
            <%= addresses_form.label :city %>
            <%= addresses_form.text_field :city %>
            <%= addresses_form.label :state %>
            <%= addresses_form.text_field :state %>
            <%= addresses_form.label :postcode %>
            <%= addresses_form.text_field :postcode %>
        </li>
        <br>
    <% end %>
    </ul>
    <%= form.submit %>
<% end %>
    

app/views/profiles/edit.html.erb
<h1> Edit Profile </h1>

<%= render "form", profile: @profile %>

app/views/profiles/index.html.erb
<h1> List Profiles </h1>

<section class="cards-container">
    <% @profiles.each do |profile| %>
    <div class="card">
        <h2><%= profile.name %></h2>
        <h3>Age: <%= profile.age %></h3>
        <p><%= profile.bio %></p>
        <h4>Addresses:</h4>
        <% profile.addresses.each do |address| %>
            <%= "#{address.street}, #{address.city}, #{address.state}, #{address.postcode}" %>
        <% end %>
        <%= link_to "Full Details", profile_path(profile.id) %>
    </div>
    <% end %>
</section>
<%= link_to "Add a New Profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1> New Profile </h1>
<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<h2>Name: <%= @profile.name %></h2>
<h2>Age: <%= @profile.age %></h2>
<h2>Bio: </h2>
<p><%= @profile.bio %>

<h2>Addresses</h2>
<% @profile.addresses.each do |address| %>
  <%= "#{address.street}, #{address.city}, #{address.state}, #{address.postcode}" %>
  <br>
<% end %>

<br>
<%= button_to "Delete Profile", {action: "destroy", id: @profile.id}, {method: :delete, class: "danger button", data: {confirm: "Are you sure you want to delete this profile?"}} %>
<%= button_to "Edit Profile", {action: "edit", id: @profile.id}, {method: :get, class: "warning button"} %>
<%= link_to "Back", profiles_path %>